### PR TITLE
Added multilevel navigation.

### PR DESCRIPTION
**Pull request by keimlink**
Multilevel navigation allows to have more than a single navigation level.

### CODE REVIEW

**Comment by dbrgn** [comment]
Wow, this is great! :) I'll comment some issues inline.

**Comment by dbrgn** [comment]
Looks good to me, besides the issues I commented inline. I'm not working on the project for which I created this app anymore, so I can't test it properly, but I assume if you're using it everything will work fine :thumbsup: :sparkles: 

Maybe we could also add a "Recipes" section to the docs, containing typical use cases (hierarchical navigation, breadcrumbs etc...) Oh, and maybe a convenience function to generate breadcrumbs would be nice.

**Comment by keimlink** [comment]
The project we are using it for is not finished yet. But my tests with the code were successful so far.

Adding a recipe section to the docs and some helper functions/template tags sounds like a good idea.

Next thing on my agenda is to add "weight" to all tabs so that they are sortable.

**Comment by dbrgn** [comment]
Sounds good! :) I'll probably migrate another project of mine that currently uses template tag hacks over to django-tabination. Then I'll also be able to use the multilevel navigation.

**Comment by keimlink** [comment]
Updated pull request.

**Comment by dbrgn** [comment]
Thanks!

**Comment by dbrgn** [comment]
v0.2.0 including multi level navigation is on pypi. I also tuned the docs a little.

**Comment by keimlink** [comment]
w00t!

**Pull request merged**
